### ISSUE TITLE
Create checklist to measure use of open source

### ISSUE THREAD

**Issue by sgort** [MinBZK/Open-Source-Program-Office#10]
Offers a checklist to 'measure' the use of open source:

- [ ] license
- [ ] number of frameworks used
- [ ] number of contributors
- [ ] number of pull requests
- [ ] number of issues
- [ ] number of forks
- [ ] number of vulnerabilities
- [ ] developers known?
- [ ] support type(s)
